### ISSUE TITLE
npm ERR! code ERR_STREAM_WRITE_AFTER_END

### ISSUE THREAD

**Issue by hamoid** [CreativeCodeBerlin/OTSParty2018#1]
I'll search for this `npm install` error later:

```
npm ERR! code ERR_STREAM_WRITE_AFTER_END
npm ERR! write after end
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fp/.npm/_logs/2018-05-22T08_04_36_444Z-debug.log
```

In the log file:
```
...
2572 2386 http fetch GET 200 https://registry.npmjs.org/p5/-/p5-0.6.1.tgz 1678ms
2573 2387 silly extract ajv@5.5.2 extracted to /home/fp/Desktop/work/2018_07_otsparty/OTSParty2018/node_modules/.staging/ajv-042ac3ea (265ms)                            
2574 2388 silly extract p5@0.6.1 extracted to /home/fp/Desktop/work/2018_07_otsparty/OTSParty2018/node_modules/.staging/p5-07c706c3 (1716ms)
2575 2389 silly extract lodash@3.10.1 extracted to /home/fp/Desktop/work/2018_07_otsparty/OTSParty2018/node_modules/.staging/lodash-b95eaf68 (344ms)
2576 2390 http fetch GET 200 https://registry.npmjs.org/xmlhttprequest-ssl/-/xmlhttprequest-ssl-1.5.5.tgz 1813ms
2577 2391 silly extract xmlhttprequest-ssl@1.5.5 extracted to /home/fp/Desktop/work/2018_07_otsparty/OTSParty2018/node_modules/.staging/xmlhttprequest-ssl-0b7d31ce           (1851ms)
2578 2392 verbose stack Error [ERR_STREAM_WRITE_AFTER_END]: write after end
2579 2392 verbose stack     at writeAfterEnd (_stream_writable.js:243:12)
2580 2392 verbose stack     at PassThrough.Writable.write (_stream_writable.js:292:5)
2581 2392 verbose stack     at PassThrough.Writable.end (_stream_writable.js:582:10)
2582 2392 verbose stack     at ReadEntry.entry.on (/usr/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
2583 2392 verbose stack     at ReadEntry.emit (events.js:187:15)
2584 2392 verbose stack     at ReadEntry.emit (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
2585 2392 verbose stack     at ReadEntry.[maybeEmitEnd] (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:249:12)
2586 2392 verbose stack     at ReadEntry.end (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:162:27)
2587 2392 verbose stack     at Unpack.[consumeBody] (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
2588 2392 verbose stack     at Unpack.[consumeChunkSub] (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
2589 2392 verbose stack     at Unpack.[consumeChunk] (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:362:30)
2590 2392 verbose stack     at Unzip.(anonymous function).on.chunk (/usr/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
2591 2392 verbose stack     at Unzip.emit (events.js:182:13)
2592 2392 verbose stack     at Unzip.emit (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:296:25)
2593 2392 verbose stack     at Unzip.write (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:99:17)
2594 2392 verbose stack     at Unzip.write (/usr/lib/node_modules/npm/node_modules/tar/node_modules/minizlib/index.js:284:29)
2595 2393 verbose cwd /home/fp/Desktop/work/2018_07_otsparty/OTSParty2018
2596 2394 verbose Linux 4.16.9-1-ARCH
2597 2395 verbose argv "/usr/bin/node" "/bin/npm" "install"
2598 2396 verbose node v10.1.0
2599 2397 verbose npm  v6.0.1
2600 2398 error code ERR_STREAM_WRITE_AFTER_END
2601 2399 error write after end
2602 2400 verbose exit [ 1, true ]
```

**Comment by hamoid** [comment]
I tried one day later and it was working... closing
